name: Deploy Agentive (Staging)

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Docker is available
        run: docker --version

      - name: Build Docker image
        run: docker build -t agentive:${{ github.sha }} .
